<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Car;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        // Sample cars data based on the frontend sample data
        $cars = [
            [
                'category' => 'economy',
                'brand' => 'Toyota',
                'model' => 'Corolla',
                'seats' => 5,
                'gearType' => 'Automatic',
                'mileage' => 15000,
                'pricePerDay' => 350.00,
                'availability' => true,
                'fuelType' => 'Hybrid',
                'color' => 'White',
                'year' => 2022,
                'image' => '/assets/deals-12.png',
                'insuranceExpiryDate' => '2024-12-31',
                'serviceDueDate' => '2024-06-15',
                'features' => json_encode(['Bluetooth', 'Backup Camera', 'USB Port', 'Navigation', 'Cruise Control']),
            ],
            [
                'category' => 'economy',
                'brand' => 'Honda',
                'model' => 'Civic',
                'seats' => 5,
                'gearType' => 'Automatic',
                'mileage' => 25000,
                'pricePerDay' => 380.00,
                'availability' => true,
                'fuelType' => 'Gasoline',
                'color' => 'Silver',
                'year' => 2021,
                'image' => '/assets/deals-10.png',
                'insuranceExpiryDate' => '2024-10-15',
                'serviceDueDate' => '2024-05-20',
                'features' => json_encode(['Bluetooth', 'Backup Camera', 'USB Port', 'Apple CarPlay']),
            ],
            [
                'category' => 'luxury',
                'brand' => 'BMW',
                'model' => '3 Series',
                'seats' => 5,
                'gearType' => 'Automatic',
                'mileage' => 8000,
                'pricePerDay' => 850.00,
                'availability' => false,
                'fuelType' => 'Gasoline',
                'color' => 'Black',
                'year' => 2023,
                'image' => '/assets/deals-15.png',
                'insuranceExpiryDate' => '2025-01-20',
                'serviceDueDate' => '2024-07-10',
                'features' => json_encode([
                    'Bluetooth',
                    'Backup Camera',
                    'USB Port',
                    'Navigation',
                    'Heated Seats',
                    'Sunroof',
                    'Leather Seats',
                    'Wireless Charging',
                ]),
            ],
            [
                'category' => 'luxury',
                'brand' => 'Mercedes-Benz',
                'model' => 'C-Class',
                'seats' => 5,
                'gearType' => 'Automatic',
                'mileage' => 12000,
                'pricePerDay' => 900.00,
                'availability' => true,
                'fuelType' => 'Hybrid',
                'color' => 'Silver',
                'year' => 2022,
                'image' => '/assets/deals-14.png',
                'insuranceExpiryDate' => '2024-11-30',
                'serviceDueDate' => '2024-08-15',
                'features' => json_encode([
                    'Bluetooth',
                    'Backup Camera',
                    'USB Port',
                    'Navigation',
                    'Heated Seats',
                    'Sunroof',
                    'Leather Seats',
                    'Wireless Charging',
                    'Premium Sound System',
                ]),
            ],
            [
                'category' => 'economy',
                'brand' => 'Hyundai',
                'model' => 'Elantra',
                'seats' => 5,
                'gearType' => 'Automatic',
                'mileage' => 30000,
                'pricePerDay' => 320.00,
                'availability' => false,
                'fuelType' => 'Gasoline',
                'color' => 'Blue',
                'year' => 2021,
                'image' => '/assets/deals-11.png',
                'insuranceExpiryDate' => '2024-09-25',
                'serviceDueDate' => '2024-04-10',
                'features' => json_encode(['Bluetooth', 'Backup Camera', 'USB Port', 'Android Auto']),
            ],
            [
                'category' => 'luxury',
                'brand' => 'Audi',
                'model' => 'A4',
                'seats' => 5,
                'gearType' => 'Automatic',
                'mileage' => 18000,
                'pricePerDay' => 780.00,
                'availability' => true,
                'fuelType' => 'Gasoline',
                'color' => 'Gray',
                'year' => 2022,
                'image' => '/assets/deals-13.png',
                'insuranceExpiryDate' => '2024-12-15',
                'serviceDueDate' => '2024-06-30',
                'features' => json_encode(['Bluetooth', 'Backup Camera', 'USB Port', 'Navigation', 'Heated Seats', 'Sunroof', 'Leather Seats']),
            ],
            [
                'category' => 'SUV',
                'brand' => 'Toyota',
                'model' => 'RAV4',
                'seats' => 5,
                'gearType' => 'Automatic',
                'mileage' => 45000,
                'pricePerDay' => 70.00,
                'availability' => true,
                'fuelType' => 'Petrol',
                'color' => 'Black',
                'year' => 2021,
                'image' => 'cars/rav4.jpg',
                'insuranceExpiryDate' => now()->addYear(),
                'serviceDueDate' => now()->addMonths(6),
                'features' => json_encode(['GPS', 'Bluetooth', 'Air Conditioning']),
            ],
        ];

        // Create each car
        foreach ($cars as $carData) {
            Car::create($carData);
        }
    }
}
